force-app/main/default/objects/ProductSubscription_POC__c/ProductSubscription_POC__c.object-meta.xml
<CustomObject>
    <label>ProductSubscriptionBuilder</label>
    <nameField>
        <displayFormat>APS-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>ProductSubscription_POC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductSubscriptions_POC</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductSubscription_POC__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>CONSOLODATED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>RESET</fullName>
            </value>
            <value>
                <fullName>CONSOLIDATED_2.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/batchConsolidatePSItems.cls
global class batchConsolidatePSItems implements Database.Batchable<sObject> 
{
    public batchConsolidatePSItems() 
    {

    }

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query = 'Select id  from ProductSubscription_POC__c where LastModifieddate >= yesterday and Status__c != \'CONSOLODATED\' order by LastModifieddate desc limit 200';  //reevaluate limit

        return Database.getQueryLocator(query);
     }
  
     global void execute(Database.BatchableContext BC, List<sObject> scope)
     {
        list<ProductSubscription_POC__c> poc2update = new List<ProductSubscription_POC__c>();
        for(SObject psPOC :scope)
           {
            ProductSubscriptionUtility.ConsolidateItems4Subs(psPOC.id);

            //after succesfull consolidation  do a merge
            psPOC.put('Status__c','CONSOLODATED');
           }

        database.update(scope);   

     }
  
     global void finish(Database.BatchableContext BC)
     {

     }    
}