force-app/main/default/objects/Product_SubscriptionItem__c/Product_SubscriptionItem__c.object-meta.xml
<CustomObject>
    <label>Product_SubscriptionItem</label>
    <nameField>
        <displayFormat>PSI-{YYMMDD}-{0000}</displayFormat>
        <label>Product_SubscriptionItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product_SubscriptionItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_SubscriptionItem__c/fields/Parent_PS__c.field-meta.xml
<CustomField>
    <fullName>Parent_PS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent ProdSubs</label>
    <referenceTo>ProductSubscription__c</referenceTo>
    <relationshipLabel>Product_SubscriptionItems</relationshipLabel>
    <relationshipName>Product_SubscriptionItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_SubscriptionItem__c/recordTypes/Consolidated.recordType-meta.xml
<RecordType>
    <fullName>Consolidated</fullName>
    <active>true</active>
    <description>record type  of a consolidated Subscription item</description>
    <label>Consolidated</label>
</RecordType>

force-app/main/default/objects/ProductSubscription_POC__c/ProductSubscription_POC__c.object-meta.xml
<CustomObject>
    <label>ProductSubscriptionBuilder</label>
    <nameField>
        <displayFormat>APS-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>ProductSubscription_POC Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductSubscriptions_POC</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductSubscription_POC__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CREATED</fullName>
            </value>
            <value>
                <fullName>CONSOLODATED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>RESET</fullName>
            </value>
            <value>
                <fullName>CONSOLIDATED_2.0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/queueableConsolidatePSIs.cls
/***********************************************************************
this is a queueable clas which call itself several times and consolidate
yhe POC PS passed as first parameter in the constructor 
 **********************************************************************/
public with sharing class queueableConsolidatePSIs  implements Queueable
{

    List<ID> pocPSIDs = new List<ID>();
    integer pocPSCounter;

    /****************************************************************************
    when this constructor is caller recursivelly pass always the same list of IDs
    but increment the counter till reach the list size()-1
    ****************************************************************************/
    public queueableConsolidatePSIs(List<ID> pocPSs2Consolidate, Integer counter) 
    {
        System.Debug('CSABAZ start queuable for ' + pocPSs2Consolidate.size() + ' items at item: ' + counter);
        pocPSIDs = pocPSs2Consolidate;
        pocPSCounter = counter;
    }    


    public void execute(QueueableContext context) 
    {
     if(pocPSIDs == NULL || pocPSCounter >= pocPSIDs.size())
        {
        return;
        }

    ID currentPOCPS = pocPSIDs.get(pocPSCounter);
    List<Product_SubscriptionItem__c> finalConsolidatedList = ProductSubscriptionUtility.ConsolidateItems4SubsBBSUM(currentPOCPS);

    integer nrofitems = finalConsolidatedList.size(); 
    System.Debug('CSABAZ current POC: ' + currentPOCPS + ' generated ' + nrofitems + ' consolidated items');

    Set<ID> prodSubscr2Merge = new set<ID>(); //we will have always 1 item
    if(finalConsolidatedList != NULL && finalConsolidatedList.size() > 0)
       {
        Product_SubscriptionItem__c consolidatedpsi = finalConsolidatedList[0];
        if(consolidatedpsi.Parent_PS__c == NULL) { return; }

        prodSubscr2Merge.add(consolidatedpsi.Parent_PS__c); 
        ProductSubscriptionUtility.MergeAllItems2Terms(prodSubscr2Merge);    
 
        ProductSubscription_POC__c poc2c =  new ProductSubscription_POC__c(Id = currentPOCPS); 
        poc2c.status__c = 'CONSOLIDATED_2.0';
        update poc2c;
       }         

    //once this is done enqueu the new queueable for the next POC 
    if(pocPSCounter < pocPSIDs.size() -1)
       {
        System.enqueueJob(new queueableConsolidatePSIs(pocPSIDs,++pocPSCounter));  
       }

    }
    
    
}